<?php

return [
    'uoms' => [
        'Numbers, pieces, units',
        'KG',
        'Kilogram',
        'Gram',
        'MT',
        'Pound',
        '40KG',
        'Carat',
        'Liter',
        'Gallon',
        'Barrels',
        'Cubic Metre',
        'Meter',
        'Foot',
        'Square Foot',
        'Square Metre',
        'SqY',
        'KWH',
        '1000 kWh',
        'MMBTU',
        'Mega Watt',
        'NO',
        'Thousand Unit',
        'Dozen',
        'Packs',
        'Bag',
        'SET',
        'Pair',
        'Bill of lading',
        'Timber Logs',
        'Others',
    ],
];
